import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { auth } from "../../../lib/auth/lucia";
import * as context from "next/headers";
import { redirect } from "next/navigation";
import { useHydrateAtoms } from "jotai/utils";
import { UserProvider } from "@/store/user_atom";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ProtectedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const authRequest = auth.handleRequest("GET", context);
  const session = await authRequest.validate();
  if (!session) redirect("/login");

  return (
    <div>
      {children}
      <UserProvider user={session.user} />
    </div>
  );
}
